### ISSUE TITLE
[META] - Current workload

### ISSUE THREAD

**Issue by mifu666** [Mythotic-Tinker-Station/lexicon-base#3]
Checklist for the rebuild. We will need to re-add these sets to this pack for the rebuild process. If the pack reaches 666 MB (or close to) then a new pack will be made.

- [ ] 1994 Tune-Up Project = 1994tu.wad
- [ ] 3 Hours in Agony series = 3hafinal.wad, 3ha2.wad, 3ha3.wad
- [ ] 32in24-14
- [ ] 5 Rooms = 5room.wad
- [ ] 50 Shades of Doom = 50shades.wad, 50shades_mpfix.wad
- [ ] Ancient Aliens
- [ ] BTSX 1 = btsx_e1_099i9.wad
- [ ] BTSX 2 = btsx_e2a.wad, btsx_e2b.wad, btsxe2-palette.wad, btsxe2-cd-liquidpatch.v2.wad
- [ ] Bloodstain = bstain.wad
- [ ] Chainworm = chainworm.wad
- [ ] Circle of Caina = dbp_02.wad
- [ ] Claustrophobia 1024
- [ ] Claustrophobia 1024 2: The Mystery of Too Many Maps
- [ ] Community Chest 1 = cchest.wad
- [ ] Community Chest 2 = cchest2.wad
- [ ] Community Chest 3 = cchest3fix.wad
- [ ] Community Chest 4 = cchest4.wad
- [ ] Congestion 1024
- [ ] Dark Encounters
- [ ] Dimensions of the boomed = dotb_rc1.wad
- [ ] Doom 2 Redux
- [ ] Doom 2 Reloaded = d2reload.wad
- [ ] Doom 2 The Way iD Did = d2twid.wad
- [x] Doom Core = dcv.wad (Under Doom core Trilogy) 
- [ ] Doomworld Megawad Project 2015 = dmp15.wad
- [ ] Doomworld Megawad Project 2016 = dmp2016v2.wad
- [ ] Doomworld Megawad Project 2017 = dmp2017-final.wad
- [x] Epic 1
- [x] Epic 2 = epic2fix.wad
- [ ] Estranged = estrangd.wad
- [ ] Eviltech
- [ ] Extermination day (when its done)
- [ ] Forest Swords = dbp_03.wad
- [ ] Freudian Slipgate = freudslp.wad
- [ ] Going Down = gd.wad
- [ ] Hell Awakened = hellawakened.wad
- [ ] Hellbound = hellbnd-v2.wad, hellboundcomplex.v3b.wad(will need to look into fix soon)
- [ ] Hellcore = hc20.wad, hc20-coopfix.pk3
- [ ] Hellebarde = hellbrd.wad
- [ ] Herian 2 = herian2-v2.wad, herian2-complexpatch.v1.wad
- [ ] Interception
- [ ] Japanese Community Compilation Project = jpcp.wad, jpcp_coopfix.wad
- [ ] Jenesis = jenesis.wad, jenefix.wad
- [x] Khorus's Speedy Shit
- [ ] Lunatic = lunatic.wad (this has a complex patch if you need it from me or it might be on tspg. (lunatic-complexpatch.v1.wad)
- [ ] Maps of Chaos
- [x] Mayhem 17
- [ ]  Mayhem 12
- [ ] Mayhem 2013
- [ ] Mayhem 16
- [ ] Mayhem 2008
- [ ] mayhem1500v1-50
- [ ] Monuments of Mars = dbp_01.wad
- [ ] Moonblood = moonbld.wad
- [ ] Mutiny = mutiny.wad
- [ ] Necrophobia = necropia2010.wad
- [ ] New Doom Community Pack 2 = ndcp2.wad
- [ ] Nova I
- [ ] Nova II = nova2.wad
- [ ] Resurgence = resurge.wad
- [ ] Space Wars = spacwars.wad
- [ ] Sparta 2 - Project Vesuvious = s2pv.wad
- [ ] Stardate 20x6 = stardate20x6.wad
- [ ] Stardate 20x7 = sd20x7.wad
- [ ] Suitcase of Gor = suitcase-v2.wad
- [ ] Sunlust = sunlust.wad (What a bitch)
- [ ] TNT Re-Evilution = tntr.wad
- [ ] Tangerine nightmare = tn.wad
- [ ] UAC Ultra = uacultra.wad, uacultravfix.wad
- [ ] Unholy Realms = ur_final.wad
- [ ] Urania = urania.wad
- [ ] Valiant (vanilla/non-vanilla) = valve.wad valient.wad - i think?
- [ ] War DSV = war_3.wad
- [ ] Zone 300
- [ ] Zones of Fear
